# Generated by Django 5.0.9 on 2025-07-13 02:59

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_medicalprofessional_available_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofessional',
            name='image_caption',
            field=models.CharField(default='profile picture', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalprofessional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=doctor.models.medicalprofessional_image_path),
        ),
    ]
