# Generated by Django 5.0.9 on 2025-04-01 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='available_doctors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_medical_professional': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
