# Generated by Django 5.0.9 on 2025-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_service_available_doctors'),
        ('doctor', '0002_alter_medicalprofessional_available_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctor_details',
            field=models.ManyToManyField(blank=True, to='doctor.medicalprofessional'),
        ),
    ]
