# Generated by Django 5.0.9 on 2025-05-27 02:12

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_service_doctor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billing_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=10, prefix='', unique=True),
        ),
    ]
