# Generated by Django 5.0.9 on 2025-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(null=True),
        ),
    ]
