# Generated by Django 5.0.9 on 2025-01-16 16:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='user',
        ),
        migrations.DeleteModel(
            name='MedicalRecords',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Prescriptions',
        ),
        migrations.DeleteModel(
            name='VideoCallSession',
        ),
        migrations.DeleteModel(
            name='MedicalProfessional',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.CreateModel(
            name='MedicalProfessional',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.useraccount',),
            managers=[
                ('medical_professional', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.useraccount',),
            managers=[
                ('patient', django.db.models.manager.Manager()),
            ],
        ),
    ]
