# Generated by Django 5.0.9 on 2025-01-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_appointments_remove_medicalprofessional_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_type',
            new_name='role',
        ),
    ]
