# Generated by Django 5.0.9 on 2025-01-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_type_useraccount_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalProfessional',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
