# Generated by Django 5.0.9 on 2025-05-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='verified',
        ),
    ]
