# Generated by Django 5.0.9 on 2025-05-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='location',
        ),
    ]
