# Generated by Django 5.0.9 on 2025-07-13 02:59

import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patient_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image_caption',
            field=models.CharField(default='profile picture', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=patient.models.patient_image_path),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_information',
            field=models.FileField(null=True, upload_to='patient/medical_info'),
        ),
    ]
