# Generated by Django 5.0.9 on 2025-01-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.DeleteModel(
            name='MedicalRecords',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Prescriptions',
        ),
        migrations.DeleteModel(
            name='VideoCallSession',
        ),
    ]
