# Generated by Django 5.0.9 on 2024-12-28 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfessional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('medical_license', models.IntegerField()),
                ('years_of_experience', models.PositiveIntegerField(max_length=50)),
                ('professional_certificate', models.FileField(null=True, upload_to='')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(max_length=150)),
                ('emergency_contact', models.TextField()),
                ('medical_information', models.FileField(null=True, upload_to='src/uploads/patient')),
            ],
        ),
    ]
