# Generated by Django 5.0.9 on 2024-12-30 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_medicalprofessional_professional_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofessional',
            name='specialty',
            field=models.CharField(default='Emergency Responder', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalprofessional',
            name='gender',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='medicalprofessional',
            name='medical_license',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Medical license must contain only uppercase letters, numbers, or hyphens.', regex='^[A-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='medicalprofessional',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='medicalprofessional',
            name='years_of_experience',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
