# Generated by Django 5.0.9 on 2025-01-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_useraccount_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalprofessional',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelManagers(
            name='medicalprofessional',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='password',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='username',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
    ]
