# Generated by Django 5.0.9 on 2025-01-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_medicalprofessional_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='is_medical_professional',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_patient',
        ),
    ]
