# Generated by Django 5.0.9 on 2025-09-03 22:30

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
