###
POST http://127.0.0.1:8000/api/signup-patient/ HTTP/1.1
Content-Type: application/json

{
  "username": "tusha",
  "last_name": "Jaken",
  "password": "Miami2_",
  "email": "tyson@tu.ge",
  "phone_number": "(486) 611-7431",
  "gender": "Male",
  "location": "USA",
  "date_of_birth": "1985-03-17",
  "age": 41
}

###
GET http://127.0.0.1:8000/api/patients/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

# {
#     "title": "mr",
#     "first_name": "house",
#     "last_name": "dolittle",
#     "email": "house@gmail.com",
#     "phone_number": "0751426582",
#     "gender": "male",
#     "medical_license": "51352547889",
#     "specialty": "doctor",
#     "years_of_experience": 25,
# }

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "dera",
    "password": "Manuel771442_"
}

###
curl \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"username": "dera", "password": "Manuel771442_"}' \
  http://localhost:8000/api/token/

