name: Deploy

on:
    workflow_run:
      workflows: ["Test and build"]
      types:
        - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - run: docker compose up --build --tag telmed-backend:v1 .
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::074124924163:role/push-to-ecr
            aws-region: us-east-1
        - name: Push to ECR
          id: ecr
          uses: jwalton/gh-ecr-push@v2
          with:
            access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: us-east-1
            local-image: telmed-backend:v1
            image: telmed-backend:v1, telmed-backend:latest
