name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/src/requirements.txt

      - name: Run tests
        run: python backend/src/manage.py test

  deploy: 
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - name: echo hello world
        run: echo 'hello world'